// src/components/Header/codeSnippets.js

/* ===================== СНИППЕТЫ КОДА ДЛЯ АНИМАЦИИ ===================== */
/* --- Реальный код из проекта, будет подсвечен через Prism.js --- */

export const snippets = [
  // --- React компоненты ---
  `import { motion } from 'framer-motion'`,
  `const [isOpen, setIsOpen] = useState(false)`,
  `export default function Header()`,
  `<AnimatePresence mode="wait">`,
  `const location = useLocation()`,
  `<Routes location={location}>`,
  `<NavLink to="/" end>`,
  `({ isActive }) => isActive ? styles.active : ''`,
  `<motion.nav variants={sidebarVariants}>`,
  `initial="hidden" animate="visible"`,
  `transition: { duration: 0.5, ease: 'easeOut' }`,
  `const footerVariants = { hidden: { y: '100%' } }`,
  `target="_blank" rel="noopener noreferrer"`,
  `aria-label={label}`,
  `{socialLinks.map(({ href, Icon, label, color }) =>`,
  `<Icon color={color} />`,
  `import styles from './Header.module.css'`,
  `createRoot(document.getElementById('root'))`,
  `<StrictMode><App /></StrictMode>`,
  `const navItems = [{ to: '/', label: 'Anschreiben' }]`,

  // --- React функции и хуки ---
  `const [data, setData] = useState(null)`,
  `useEffect(() => { fetchData() }, [])`,
  `const handleClick = useCallback(() => {}, [])`,
  `const memoValue = useMemo(() => compute(), [dep])`,
  `const ref = useRef(null)`,
  `useContext(ThemeContext)`,
  `const navigate = useNavigate()`,
  `navigate('/about', { replace: true })`,
  `const { id } = useParams()`,
  `throw new Error('Something went wrong')`,
  `React.lazy(() => import('./Page'))`,
  `<Suspense fallback={<Spinner />}>`,
  `forwardRef((props, ref) => <div ref={ref} />)`,
  `React.memo(function Component() {})`,
  `useReducer(reducer, initialState)`,

  // --- CSS ---
  `display: flex; align-items: center;`,
  `backdrop-filter: var(--blur)`,
  `background: var(--color-surface)`,
  `border-radius: var(--radius)`,
  `transition: all var(--transition)`,
  `grid-template-columns: 1fr 14em`,
  `overflow-y: auto`,
  `@media (max-width: 48em)`,
  `flex-direction: column-reverse`,
  `gap: var(--space-md)`,
  `font-family: var(--font-heading)`,
  `color: var(--color-accent)`,
  `opacity: 0.75`,
  `transform: translateY(-0.2em)`,
  `border: 0.1em solid var(--color-border)`,

  // --- CSS функции ---
  `clamp(1rem, 2.5vw, 2rem)`,
  `calc(100vh - 4em)`,
  `var(--color-accent, #4a90b8)`,
  `linear-gradient(135deg, #f0f4f8, #dce6f0)`,
  `rgba(255, 255, 255, 0.6)`,
  `minmax(0, 1fr)`,
  `repeat(auto-fit, minmax(16em, 1fr))`,
  `cubic-bezier(0.4, 0, 0.2, 1)`,
  `scale(1.05) translateY(-0.2em)`,
  `blur(12px) saturate(180%)`,

  // --- Java / Spring Boot ---
  `@RestController @RequestMapping("/api")`,
  `@GetMapping("/memorial/{id}")`,
  `ResponseEntity<MemorialDto> getById`,
  `@Autowired private JwtService jwtService`,
  `return ResponseEntity.ok(service.findAll())`,
  `@Entity @Table(name = "memorials")`,
  `@GeneratedValue(strategy = AUTO)`,
  `private String accessToken`,
  `filterChain.doFilter(request, response)`,
  `@PostMapping("/auth/refresh")`,

  // --- Java функции и паттерны ---
  `Optional<User> findById(Long id)`,
  `stream().filter(x -> x.isActive())`,
  `.map(UserMapper::toDto).collect(toList())`,
  `@Transactional(rollbackFor = Exception.class)`,
  `throw new ResourceNotFoundException("Not found")`,
  `@Valid @RequestBody MemorialRequest req`,
  `jwtService.generateToken(userDetails)`,
  `Claims claims = Jwts.parser().parseClaimsJws(token)`,
  `@Scheduled(fixedDelay = 60000)`,
  `CompletableFuture.supplyAsync(() -> process())`,
  `@ExceptionHandler(NotFoundException.class)`,
  `List<Memorial> findAllByUserId(Long userId)`,
  `BCryptPasswordEncoder().encode(password)`,
  `@OneToMany(mappedBy = "user", cascade = ALL)`,
  `publisher.publishEvent(new MemorialCreatedEvent(this))`,
]